import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { getListing } from '@/lib/airtable/listings'
import { getContentByListing } from '@/lib/airtable/content'
import type { ApiResponse } from '@/types/api'
import type { ContentType } from '@/types/content'

const resend = new Resend(process.env.RESEND_API_KEY)
const FROM = 'FramePostReady <onboarding@resend.dev>'

const TYPE_EMOJI: Record<ContentType, string> = {
  Instagram: '📸',
  Facebook: '📘',
  MLS: '🏠',
  Email: '✉️',
  'Reel Script': '🎬',
  Hashtags: '#️⃣',
}

const CONTENT_ORDER: ContentType[] = ['Instagram', 'Facebook', 'MLS', 'Email', 'Reel Script', 'Hashtags']

function buildContentPackHtml(listing: Awaited<ReturnType<typeof getListing>>, blocks: Awaited<ReturnType<typeof getContentByListing>>) {
  if (!listing) return ''

  const blockMap = Object.fromEntries(blocks.map((b) => [b.contentType, b]))

  const contentSections = CONTENT_ORDER.map((type) => {
    const block = blockMap[type]
    if (!block) return ''
    return `
      <div style="margin-bottom:32px; padding:20px; background:#f9fafb; border-radius:8px; border:1px solid #e5e7eb;">
        <h3 style="margin:0 0 12px; font-size:15px; color:#374151;">${TYPE_EMOJI[type]} ${type}</h3>
        <pre style="margin:0; font-family:inherit; font-size:13px; line-height:1.7; color:#111827; white-space:pre-wrap; word-break:break-word;">${escapeHtml(block.generatedText)}</pre>
      </div>
    `
  }).join('')

  return `
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"/></head>
    <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; max-width:680px; margin:0 auto; padding:32px 16px; color:#111827;">
      <div style="border-bottom:2px solid #111827; padding-bottom:20px; margin-bottom:28px;">
        <h1 style="margin:0; font-size:22px; font-weight:700;">${escapeHtml(listing.address)}</h1>
        <p style="margin:6px 0 0; font-size:14px; color:#6b7280;">${escapeHtml(listing.city)}${listing.county ? `, ${listing.county}` : ''} · $${listing.price.toLocaleString()} · ${listing.beds}bd/${listing.baths}ba · ${listing.sqft.toLocaleString()} sqft</p>
        ${listing.tone ? `<p style="margin:4px 0 0; font-size:13px; color:#9ca3af;">Tone: ${listing.tone}${listing.targetBuyer ? ` · Target: ${listing.targetBuyer}` : ''}</p>` : ''}
      </div>

      <p style="font-size:13px; color:#6b7280; margin:0 0 24px;">Generated by FramePostReady · Frame &amp; Form Studio · ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

      ${contentSections}

      <div style="margin-top:32px; padding-top:20px; border-top:1px solid #e5e7eb; font-size:12px; color:#9ca3af; text-align:center;">
        FramePostReady · Frame &amp; Form Studio · All content is AI-generated. Review before publishing.
      </div>
    </body>
    </html>
  `
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { listingId, recipientEmail } = body

    if (!listingId) {
      return NextResponse.json<ApiResponse>({ success: false, error: 'listingId is required' }, { status: 400 })
    }
    if (!recipientEmail) {
      return NextResponse.json<ApiResponse>({ success: false, error: 'recipientEmail is required' }, { status: 400 })
    }

    const [listing, blocks] = await Promise.all([
      getListing(listingId),
      getContentByListing(listingId),
    ])

    if (!listing) {
      return NextResponse.json<ApiResponse>({ success: false, error: 'Listing not found' }, { status: 404 })
    }
    if (blocks.length === 0) {
      return NextResponse.json<ApiResponse>({ success: false, error: 'No content generated for this listing yet' }, { status: 400 })
    }

    const html = buildContentPackHtml(listing, blocks)

    const { error } = await resend.emails.send({
      from: FROM,
      to: [recipientEmail],
      subject: `📦 Content Pack — ${listing.address}, ${listing.city}`,
      html,
    })

    if (error) throw new Error(error.message)

    console.log(`[export] Content pack sent to ${recipientEmail} for listing ${listingId}`)

    return NextResponse.json<ApiResponse>({ success: true, message: `Content pack sent to ${recipientEmail}` })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Export failed'
    console.error('[POST /api/export]', message)
    return NextResponse.json<ApiResponse>({ success: false, error: message }, { status: 500 })
  }
}
