'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import type { Listing } from '@/types/listing'
import type { ContentType } from '@/types/content'

interface ContentBlock {
  id: string
  contentType: ContentType
  generatedText: string
  version: number
}

const TYPE_EMOJI: Record<ContentType, string> = {
  Instagram: '📸',
  Facebook: '📘',
  MLS: '🏠',
  Email: '✉️',
  'Reel Script': '🎬',
  Hashtags: '#️⃣',
}

const CONTENT_ORDER: ContentType[] = ['Instagram', 'Facebook', 'MLS', 'Email', 'Reel Script', 'Hashtags']

export default function ExportPage() {
  const params = useParams()
  const listingId = params.id as string

  const [listing, setListing] = useState<Listing | null>(null)
  const [blocks, setBlocks] = useState<ContentBlock[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function load() {
      const [listingRes, contentRes] = await Promise.all([
        fetch(`/api/listings/${listingId}`),
        fetch(`/api/content?listingId=${listingId}`),
      ])
      const listingJson = await listingRes.json()
      const contentJson = await contentRes.json()
      if (listingJson.success) setListing(listingJson.data)
      if (contentJson.success) setBlocks(contentJson.data || [])
      setLoading(false)
    }
    load()
  }, [listingId])

  const blockMap = Object.fromEntries(blocks.map((b) => [b.contentType, b]))

  if (loading) {
    return <div className="min-h-screen flex items-center justify-center text-gray-400 text-sm">Loading...</div>
  }

  if (!listing) return null

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-8 py-10">

        <div className="print:hidden flex items-center justify-between mb-8">
          <Link href={`/listings/${listingId}`} className="text-sm text-gray-400 hover:text-gray-600">
            ← Back to listing
          </Link>
          <button
            onClick={() => window.print()}
            className="bg-gray-900 hover:bg-gray-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
          >
            🖨️ Print / Save as PDF
          </button>
        </div>

        <div className="border-b-2 border-gray-900 pb-6 mb-8">
          <h1 className="text-2xl font-bold text-gray-900">{listing.address}</h1>
          <p className="text-sm text-gray-500 mt-1">
            {listing.city}{listing.county ? `, ${listing.county}` : ''} · ${listing.price.toLocaleString()} · {listing.beds}bd/{listing.baths}ba · {listing.sqft.toLocaleString()} sqft
          </p>
          {listing.tone && (
            <p className="text-xs text-gray-400 mt-1">
              Tone: {listing.tone}{listing.targetBuyer ? ` · Target: ${listing.targetBuyer}` : ''}
            </p>
          )}
        </div>

        <p className="text-xs text-gray-400 mb-8">
          Generated by FramePostReady · Frame &amp; Form Studio · {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <div className="space-y-8">
          {CONTENT_ORDER.map((type) => {
            const block = blockMap[type]
            if (!block) return (
              <div key={type} className="p-5 border border-dashed border-gray-200 rounded-lg text-sm text-gray-400">
                {type} — not generated
              </div>
            )
            return (
              <div key={type} className="break-inside-avoid">
                <div className="flex items-center gap-2 mb-3">
                  <span className="text-lg">{TYPE_EMOJI[type]}</span>
                  <h2 className="font-semibold text-gray-900 text-base">{type}</h2>
                </div>
                <div className="bg-gray-50 rounded-lg p-5 border border-gray-200">
                  <pre className="text-sm text-gray-800 whitespace-pre-wrap font-sans leading-relaxed break-words">
                    {block.generatedText}
                  </pre>
                </div>
              </div>
            )
          })}
        </div>

        <div className="mt-12 pt-6 border-t border-gray-200 text-xs text-gray-400 text-center">
          FramePostReady · Frame &amp; Form Studio · All content is AI-generated. Review before publishing.
        </div>

      </div>
    </div>
  )
}
